service: cart-user-order-service

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  timeout: 10
  httpApi:
    cors: true
  environment:
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_PORT: ${env:POSTGRES_PORT}
    POSTGRES_USER: ${env:POSTGRES_USER}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_DB: ${env:POSTGRES_DB}
    POSTGRES_SCHEMA: ${env:POSTGRES_SCHEMA}
package:
  individually: true

functions:
  main:
    handler: dist/main.handler
    events:
      - httpApi:
          method: ANY
          path: '/{proxy+}'