export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const CARTS_REPOSITORY = 'CARTS_REPOSITORY';
export const CART_ITEMS_REPOSITORY = 'CART_ITEMS_REPOSITORY';
export const PRODUCTS_REPOSITORY = 'PRODUCTS_REPOSITORY'